# permissions for end users to view attributesyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: attributesync-viewer-role
rules:
- apiGroups:
  - keycloak.appuio.ch
  resources:
  - attributesyncs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keycloak.appuio.ch
  resources:
  - attributesyncs/status
  verbs:
  - get
