# permissions for end users to edit attributesyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: attributesync-editor-role
rules:
- apiGroups:
  - keycloak.appuio.ch
  resources:
  - attributesyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keycloak.appuio.ch
  resources:
  - attributesyncs/status
  verbs:
  - get
